# Generated by Django 4.1.6 on 2023-02-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=50)),
                ('BankId', models.IntegerField()),
                ('BankAddress', models.TextField()),
                ('AccountNumber', models.IntegerField()),
                ('Branchname', models.CharField(max_length=50)),
                ('IFSCCode', models.IntegerField()),
                ('SwiftCode', models.IntegerField()),
                ('PaypalID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCompanyName', models.CharField(max_length=50)),
                ('pointofcontact', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('GstNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('countrycode', models.IntegerField()),
                ('ClientId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('companyLogo', models.ImageField(upload_to='images')),
                ('eamailID', models.EmailField(max_length=254)),
                ('contactNumber', models.IntegerField()),
                ('GSTNumber', models.JSONField()),
                ('PANNumber', models.JSONField()),
                ('LUTNumber', models.URLField()),
                ('adress', models.TextField()),
                ('country', models.BinaryField()),
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.IntegerField()),
                ('RateonDate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MssandNda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.IntegerField()),
                ('Clientname', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('Enddate', models.DateField()),
                ('Documentid', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('docupload', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterid', models.IntegerField()),
                ('Description', models.CharField(max_length=50)),
                ('CurrencyRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('PointofContact', models.IntegerField()),
                ('Solution', models.IntegerField()),
                ('Service', models.IntegerField()),
                ('ProjectName', models.TextField()),
                ('PORef', models.CharField(max_length=50)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Currency', models.IntegerField()),
                ('ProjectValue', models.IntegerField()),
                ('ProjectId', models.IntegerField()),
                ('projectStatus', models.CharField(max_length=50)),
                ('projectuploadpdf', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestoneid', models.IntegerField()),
                ('milestoneNoteRemark', models.IntegerField()),
                ('milestonehours', models.TimeField()),
                ('milestoneValue', models.IntegerField()),
                ('convertionrate', models.IntegerField()),
                ('status', models.IntegerField()),
                ('InvoiceNo', models.IntegerField()),
                ('InvoiceDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('MilestoneDate', models.DateField()),
                ('Milestonevalue', models.IntegerField()),
                ('Milestoneupdate', models.DateField()),
                ('Milestoneid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestoneid', models.IntegerField()),
                ('paymentDate', models.DateField()),
                ('paymentValue', models.IntegerField()),
                ('PaymentNote', models.CharField(max_length=50)),
            ],
        ),
    ]
