# Generated by Django 4.1.6 on 2023-02-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='GSTNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='LUTNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='PANNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='', upload_to='bics11.avif/images'),
        ),
    ]
