# Generated by Django 4.1.7 on 2023-02-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0003_remove_bank_id_remove_client_id_remove_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='my_picture'),
        ),
    ]
