# Generated by Django 4.1.7 on 2023-03-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0004_company_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='CompanyID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CompanyID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='CompanyID',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='mssandnda',
            name='companyid',
        ),
        migrations.AlterField(
            model_name='bank',
            name='BankId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mssandnda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectId',
            field=models.CharField(max_length=50),
        ),
    ]
