# Generated by Django 4.1.7 on 2023-03-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0005_rename_companyid_bank_id_rename_companyid_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ProjectId',
            new_name='Projectid',
        ),
    ]
