# Generated by Django 4.1.7 on 2023-03-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0007_alter_projectinvoices_invoiceno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinvoices',
            old_name='InvoiceDate',
            new_name='Invoicedate',
        ),
        migrations.RenameField(
            model_name='projectinvoices',
            old_name='InvoiceNo',
            new_name='Invoiceno',
        ),
    ]
