# Generated by Django 4.1.7 on 2023-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=120)),
                ('workdescription', models.TextField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('workhours', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
